[workspace.package]
version = "0.1.0"
description = "Bottles Next is the evolution of Bottles"
authors = ["Eduardo Flores <edfloreshz@proton.me", "Inam Ul Haq <inam123451@gmail.com>"]
edition = "2024"
license = "GPL-3.0"
repository = "https://github.com/bottlesdevs/bottles-next"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]
readme = "README.md"

[workspace]
members = [
    "crates/download-manager",
    "crates/fvs2-rs",
    "crates/http-client",
    "crates/next-cli",
    "crates/next-core",
    "crates/next-config",
    "crates/next-server",
    "crates/next-ui",
    "crates/next-proto",
    "crates/next-winebridge",
    "crates/next-plugin-egs",
    "crates/next-plugin-gog",
    "crates/next-plugin-registry",
]
default-members = [
    "crates/download-manager",
    "crates/fvs2-rs",
    "crates/http-client",
    "crates/next-cli",
    "crates/next-core",
    "crates/next-config",
    "crates/next-server",
    "crates/next-ui",
    "crates/next-proto",
    "crates/next-winebridge",
    "crates/next-plugin-egs",
    "crates/next-plugin-gog",
    "crates/next-plugin-registry",
]
resolver = "3"

[workspace.dependencies]
async-fs = "2.2"
async-broadcast = "0.7"
async-channel = "2.5"
async-compression = { version = "0.4", default-features = false, features = ["futures-io", "gzip", "xz"] }
async-executor = "1.13"
async-io = "2.6"
async-process = "2.5"
async-trait = "0.1"
blocking = "1.6"
bottles-core = { path = "crates/next-core" }
chrono = "0.4"
download-manager = { path = "crates/download-manager" }
fvs-rs = { path = "crates/fvs2-rs" }
next-config = { path = "crates/next-config" }
next-proto = { path = "crates/next-proto" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde-value = "0.7"
serde_json = "1.0"
semver = {version = "1", features = ["serde"] }
sha2 = "0.10"
strum = { version = "0.27", features = ["derive"] }
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter", "fmt"]}
tonic = "0.14"
egs-api = "0.14.0"
gog = "0.5.0"
keyring = "4.1.6"
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14"
tonic-health = "0.14"
tonic-prost-build = "0.14"
tonic-reflection = "0.14.6"
tokio = "1.48"
tokio-stream = "0.1"
tokio-util = "0.7"
reqwest = { version = "0.12", features = ["stream"] }
futures-core = "0.3"
futures-lite = "2.6"
futures-util = "0.3"
http = "1"
http-client = { path = "crates/http-client", default-features = false }
derive_builder = "0.20"
inventory = "0.3"
uuid = { version = "1", features = ["v4"] }
url = "2"
directories = "6.0"
smol-tar = "0.1"
keyvalues-parser = "0.2.4"
notify = "8.2.0"
regdiff-rs = { git = "https://github.com/bottlesdevs/regdiff-rs", rev = "3266ab15abca4ef470b1ec5797cfeaa24e003510" }
